### ISSUE TITLE
Controller Documentation gets it wrong ....

### ISSUE THREAD

**Issue by ghost** [rk/uFramework#1]
In the [Controller](http://micro.thewickedflea.com/wiki/view/class-_controller) article in the Documentation you mention:
    class Welcome extends Controller {
      private function _setup() {
        // My setup tasks are done here...
      }
      function index() {
        // logic/views are run here.
      }
    }

This produces the following fatal error:
    Fatal error: Call to private method Welcome::_setup() from context 'Controller' in [...]\htdocs\uframework\application\u-framework.php on line 226

using a 'public' instead of 'private', does the job,... but is it the correct way to do this?

**Comment by rk** [comment]
You are correct, the controller article is currently outdated. Better documentation is pending, as is a 1.1 release. Sorry the response took so long, but I thought that I'd get an email when an issue was filed.

**Comment by ghost** [comment]
Ok, time is not an issue if there is a 1.1 release on the way :)
Maybe it could be usefull to set up git tags and commit much more often, so that people know that this is still alive :)

**Comment by rk** [comment]
I made a minor typo there, it's the first major release of 1.0 that I'm working towards. However, I have no clue how to use git tags. Part of the slowness updating is that thanks to how I originally set up the repository, it isn't a working directory; and I'm still relatively new to working with Git and source control that isn't on my system.

**Comment by ghost** [comment]
If you want you can chat me up on skype. Same username.
I am starting git exploration too and have found quite a number of helpfull links to read.

**Comment by rk** [comment]
Closing this due to the code/issue being out of date. The current controller class can simply use the `__construct()` method to do its initialization work.
