### ISSUE TITLE
Does not work in *nix

### ISSUE THREAD

**Issue by captn3m0** [rk/uFramework#3]
A default setup gives the following error :

<code>Fatal error: Cannot redeclare link() in /home/nemo/projects/uFramework/application/includes/default.php on line 34</code>

I'd have submitted a patch, but I'm not sure what you'd want to rename the function to. Probably url or makelink should be good.
This is because PHP in *nix [already has a link function](http://php.net/manual/en/function.link.php)

**Comment by rk** [comment]
You are correct. Unfortunately I don't remember receiving an error or warning when I wrote that function.

I'll be pushing a patch out with `link` as `link_to` shortly; I liked the Rails' name of the function. Nothing has changed greatly except `absolute_path`. Now `absolute_path` will `urlencode()` the passed URL as a security feature (XSS was easily accomplished by it before).
